name: build.yml
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: build-unity-project
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneLinux64
          - StandaloneOSX
          - WebGL
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build-project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          RUN_AS_HOST_USER: true
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true
          
      - name: Fix file permissions after tests
        if: always()
        run: |
          echo "Fixing permissions for files created by Unity"
          sudo chown -R $(whoami) /home/$USER/actions-runner/_work/
          chmod -R u+rwx /home/$USER/actions-runner/_work/

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
