name: Test

on: [push, pull_request]

jobs:
  test:
    name: run-unit-tests
    runs-on: self-hosted
    steps:
      - name: Checkout-repository
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Run-tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: "${{ secrets.UNITY_LICENSE }}"
          UNITY_EMAIL: "${{ secrets.UNITY_EMAIL }}"
          UNITY_PASSWORD: "${{ secrets.UNITY_PASSWORD }}"
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix file permissions after tests
        if: always()
        run: |
          echo "Fixing permissions for files created by Unity"
          sudo chown -R $(whoami) /home/$USER/actions-runner/_work/
          chmod -R u+rwx /home/$USER/actions-runner/_work/
